### ISSUE TITLE
Question: Preventing Man in the Middle attacks

### ISSUE THREAD

**Issue by nbeadman** [spreedly/mobile-sdk-ios#18]
I have an iOS mobile app that is communicating with the Spreedly core API and have noticed that it is possible to sniff network traffic using Charles Proxy/Proxyman. Given the request includes the full name, card number, CVV and ZIP of the credit card I am wondering if there is any mechanism to do HTTP Public Key Pinning, aka Cert pinning, or any other mechanism (maybe HMAC?) to protect this information?

Currently I have my own implementation of the Spreedly API requests but the same issue also occurs with the sample project in this repo.

Thanks,
Nick

**Comment by stefanrusek** [comment]
This shouldn't be necessary, since we use HTTPS. When you install Charles you also install it's SSL certificates, without which it wouldn't be able to proxy HTTPS requests. https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/

**Comment by nbeadman** [comment]
@stefanrusek Thanks for the response.

I understand that `https` is a requirement and Charles' SSL certificates need to be installed to proxy requests. However, the Spreedly API call includes full credit card number, first and last name, CVV and ZIP which is highly sensitive information. As disallowing proxying has a known solution, it seems wise for the SDK to be more secure.

**Comment by aenand** [comment]
Hey @nbeadman We have chosen to forego certificate pinning in our reference code because of the operational risk of using it is too high. We don’t have control over how folks integrate our reference code and if we start pinning certs, we’re going to run into issues with customers who aren’t fully aware and their ability to take payments will be negatively impacted.
Customers are welcome to implement their own certificate pinning in their application with the understanding that they then own management of the certificate lifecycle which itself will be problematic because we do not provide advance notice for our certificate renewals.
